const ASSET_IMAGES = {
  "2_piece.avif": new URL("../assets/stylesense-pictures/2_piece.avif", import.meta.url).href,
  "2_piece2.webp": new URL("../assets/stylesense-pictures/2_piece2.webp", import.meta.url).href,
  "casual_dress1.avif": new URL("../assets/stylesense-pictures/casual_dress1.avif", import.meta.url).href,
  "casual_dress3.avif": new URL("../assets/stylesense-pictures/casual_dress3.avif", import.meta.url).href,
  "casual_dress4.jpg": new URL("../assets/stylesense-pictures/casual_dress4.jpg", import.meta.url).href,
  "casual_women_dress1.jpg": new URL("../assets/stylesense-pictures/casual_women_dress1.jpg", import.meta.url).href,
  "casual_women_dress2.jpg": new URL("../assets/stylesense-pictures/casual_women_dress2.jpg", import.meta.url).href,
  "casual_women_dress3.jpg": new URL("../assets/stylesense-pictures/casual_women_dress3.jpg", import.meta.url).href,
  "casual_women_dress4.jpg": new URL("../assets/stylesense-pictures/casual_women_dress4.jpg", import.meta.url).href,
  "casual_women_dress5.jpg": new URL("../assets/stylesense-pictures/casual_women_dress5.jpg", import.meta.url).href,
  "former_outfit.jpg": new URL("../assets/stylesense-pictures/former_outfit.jpg", import.meta.url).href,
  "formal_women_dress1.jpg": new URL("../assets/stylesense-pictures/formal_women_dress1.jpg", import.meta.url).href,
  "formal_women_dress2.avif": new URL("../assets/stylesense-pictures/formal_women_dress2.avif", import.meta.url).href,
  "formal_women_outfit.jpg": new URL("../assets/stylesense-pictures/formal_women_outfit.jpg", import.meta.url).href,
  "jean_pant3.avif": new URL("../assets/stylesense-pictures/jean_pant3.avif", import.meta.url).href,
  "jean_pant7.jpg": new URL("../assets/stylesense-pictures/jean_pant7.jpg", import.meta.url).href,
  "maxi_dress1.jpg": new URL("../assets/stylesense-pictures/maxi_dress1.jpg", import.meta.url).href,
  "maxi_dress2.jpg": new URL("../assets/stylesense-pictures/maxi_dress2.jpg", import.meta.url).href,
  "maxi_dress3.jpg": new URL("../assets/stylesense-pictures/maxi_dress3.jpg", import.meta.url).href,
  "maxi_dress4.jpg": new URL("../assets/stylesense-pictures/maxi_dress4.jpg", import.meta.url).href,
  "maxi_dress5.jpg": new URL("../assets/stylesense-pictures/maxi_dress5.jpg", import.meta.url).href,
  "mens_sweater2.jpg": new URL("../assets/stylesense-pictures/mens_sweater2.jpg", import.meta.url).href,
  "mens_sweater4.jpg": new URL("../assets/stylesense-pictures/mens_sweater4.jpg", import.meta.url).href,
  "party_dress1.jpg": new URL("../assets/stylesense-pictures/party_dress1.jpg", import.meta.url).href,
  "party_dress2.jpg": new URL("../assets/stylesense-pictures/party_dress2.jpg", import.meta.url).href,
  "party_dress3.jpg": new URL("../assets/stylesense-pictures/party_dress3.jpg", import.meta.url).href,
  "party_dress4.jpg": new URL("../assets/stylesense-pictures/party_dress4.jpg", import.meta.url).href,
  "party_dress5.jpg": new URL("../assets/stylesense-pictures/party_dress5.jpg", import.meta.url).href,
  "skirt9.webp": new URL("../assets/stylesense-pictures/skirt9.webp", import.meta.url).href,
  "women_skirt_avif1.avif": new URL("../assets/stylesense-pictures/women_skirt_avif1.avif", import.meta.url).href,
  "women_skirt_avif2.avif": new URL("../assets/stylesense-pictures/women_skirt_avif2.avif", import.meta.url).href,
  "women_skirt_outfit1.jpg": new URL("../assets/stylesense-pictures/women_skirt_outfit1.jpg", import.meta.url).href,
  "women_skirt_outfit2.jpg": new URL("../assets/stylesense-pictures/women_skirt_outfit2.jpg", import.meta.url).href,
  "women_skirt_outfit3.jpg": new URL("../assets/stylesense-pictures/women_skirt_outfit3.jpg", import.meta.url).href,
  "women_skirt_outfit4.jpg": new URL("../assets/stylesense-pictures/women_skirt_outfit4.jpg", import.meta.url).href,
  "women_skirt_outfit5.jpg": new URL("../assets/stylesense-pictures/women_skirt_outfit5.jpg", import.meta.url).href,
  "women_skirt_style0.jpg": new URL("../assets/stylesense-pictures/women_skirt_style0.jpg", import.meta.url).href,
  "women_skirt_style3.jpg": new URL("../assets/stylesense-pictures/women_skirt_style3.jpg", import.meta.url).href,
  "women_skirt_style4.jpg": new URL("../assets/stylesense-pictures/women_skirt_style4.jpg", import.meta.url).href,
  "women_skirt_style5.jpg": new URL("../assets/stylesense-pictures/women_skirt_style5.jpg", import.meta.url).href,
  "women_skirt_style6.jpg": new URL("../assets/stylesense-pictures/women_skirt_style6.jpg", import.meta.url).href,
  "women_skirt_style7.jpg": new URL("../assets/stylesense-pictures/women_skirt_style7.jpg", import.meta.url).href,
  "mens_shoe1.jpg": new URL("../assets/stylesense-pictures/mens_shoe1.jpg", import.meta.url).href,
  "mens_shoe2.jpg": new URL("../assets/stylesense-pictures/mens_shoe2.jpg", import.meta.url).href,
  "mens_shoe3.jpg": new URL("../assets/stylesense-pictures/mens_shoe3.jpg", import.meta.url).href,
  "mens_shoe4.jpg": new URL("../assets/stylesense-pictures/mens_shoe4.jpg", import.meta.url).href,
  "mens_shoe5.jpg": new URL("../assets/stylesense-pictures/mens_shoe5.jpg", import.meta.url).href,
  "mens_shoe6.jpg": new URL("../assets/stylesense-pictures/mens_shoe6.jpg", import.meta.url).href,
  "women_winter_slip_on_boots.webp": new URL("../assets/stylesense-pictures/women_winter_slip_on_boots.webp", import.meta.url).href,
  "women_fur_winter_boots.webp": new URL("../assets/stylesense-pictures/women_fur_winter_boots.webp", import.meta.url).href,
  "women_black_knee_high_boots.webp": new URL("../assets/stylesense-pictures/women_black_knee_high_boots.webp", import.meta.url).href,
  "women_burgundy_heeled_sandals.webp": new URL("../assets/stylesense-pictures/women_burgundy_heeled_sandals.webp", import.meta.url).href,
  "women_embellished_flat_sandals.webp": new URL("../assets/stylesense-pictures/women_embellished_flat_sandals.webp", import.meta.url).href,
  "women_wedge_sandals.webp": new URL("../assets/stylesense-pictures/women_wedge_sandals.webp", import.meta.url).href,
  "accessory_gold_knot_set.webp": new URL("../assets/stylesense-pictures/accessory_gold_knot_set.webp", import.meta.url).href,
  "accessory_green_drop_earrings.webp": new URL("../assets/stylesense-pictures/accessory_green_drop_earrings.webp", import.meta.url).href,
  "accessory_ruby_necklace_set.webp": new URL("../assets/stylesense-pictures/accessory_ruby_necklace_set.webp", import.meta.url).href,
  "accessory_silver_hoop_earrings.webp": new URL("../assets/stylesense-pictures/accessory_silver_hoop_earrings.webp", import.meta.url).href,
  "accessory_gold_chain_necklace.webp": new URL("../assets/stylesense-pictures/accessory_gold_chain_necklace.webp", import.meta.url).href,
  "accessory_layered_silver_necklace.webp": new URL("../assets/stylesense-pictures/accessory_layered_silver_necklace.webp", import.meta.url).href,
  "accessory_pearl_necklace_set.webp": new URL("../assets/stylesense-pictures/accessory_pearl_necklace_set.webp", import.meta.url).href,
  "accessory_statement_silver_necklace.jpg": new URL("../assets/stylesense-pictures/accessory_statement_silver_necklace.jpg", import.meta.url).href,
  "sweater1.avif": new URL("../assets/stylesense-pictures/sweater1.avif", import.meta.url).href,
  "sweater2.avif": new URL("../assets/stylesense-pictures/sweater2.avif", import.meta.url).href,
  "sweater3.avif": new URL("../assets/stylesense-pictures/sweater3.avif", import.meta.url).href,
  "sweater4.webp": new URL("../assets/stylesense-pictures/sweater4.webp", import.meta.url).href,
  "sweater5.avif": new URL("../assets/stylesense-pictures/sweater5.avif", import.meta.url).href,
  "sweater6.jpg": new URL("../assets/stylesense-pictures/sweater6.jpg", import.meta.url).href,
  "top3.jpg": new URL("../assets/stylesense-pictures/top3.jpg", import.meta.url).href,
  "top5.webp": new URL("../assets/stylesense-pictures/top5.webp", import.meta.url).href,
  "women_top1.avif": new URL("../assets/stylesense-pictures/women_top1.avif", import.meta.url).href,
  "women_top2.avif": new URL("../assets/stylesense-pictures/women_top2.avif", import.meta.url).href,
  "women_top3.jpg": new URL("../assets/stylesense-pictures/women_top3.jpg", import.meta.url).href,
  "women_top4.jpg": new URL("../assets/stylesense-pictures/women_top4.jpg", import.meta.url).href,
  "women_top5.webp": new URL("../assets/stylesense-pictures/women_top5.webp", import.meta.url).href,
  "women_dress_top1.jpg": new URL("../assets/stylesense-pictures/women_dress_top1.jpg", import.meta.url).href,
  "women_crop_top.jpg": new URL("../assets/stylesense-pictures/women_crop_top.jpg", import.meta.url).href,
  "women_crop1.jpg": new URL("../assets/stylesense-pictures/women_crop1.jpg", import.meta.url).href,
  "women_crop2.jpg": new URL("../assets/stylesense-pictures/women_crop2.jpg", import.meta.url).href,
  "women_crop3.jpg": new URL("../assets/stylesense-pictures/women_crop3.jpg", import.meta.url).href,
  "women_crop4.jpg": new URL("../assets/stylesense-pictures/women_crop4.jpg", import.meta.url).href,
  "women_crop5.jpg": new URL("../assets/stylesense-pictures/women_crop5.jpg", import.meta.url).href,
  "women_hoodie1.jpg": new URL("../assets/stylesense-pictures/women_hoodie1.jpg", import.meta.url).href,
  "women_hoodie3.jpg": new URL("../assets/stylesense-pictures/women_hoodie3.jpg", import.meta.url).href,
  "women_hoodie5.jpg": new URL("../assets/stylesense-pictures/women_hoodie5.jpg", import.meta.url).href,
  "mens_hoodie2.jpg": new URL("../assets/stylesense-pictures/mens_hoodie2.jpg", import.meta.url).href,
  "mens_hoodie4.jpg": new URL("../assets/stylesense-pictures/mens_hoodie4.jpg", import.meta.url).href,
  "women_jacket1.jpg": new URL("../assets/stylesense-pictures/women_jacket1.jpg", import.meta.url).href,
  "women_jacket2.jpg": new URL("../assets/stylesense-pictures/women_jacket2.jpg", import.meta.url).href,
  "women_jacket5.webp": new URL("../assets/stylesense-pictures/women_jacket5.webp", import.meta.url).href,
  "mens_jacket3.jpg": new URL("../assets/stylesense-pictures/mens_jacket3.jpg", import.meta.url).href,
  "mens_jacket4.jpg": new URL("../assets/stylesense-pictures/mens_jacket4.jpg", import.meta.url).href,
  "mens_trouser1.jpg": new URL("../assets/stylesense-pictures/mens_trouser1.jpg", import.meta.url).href,
  "mens_trouser2.jpg": new URL("../assets/stylesense-pictures/mens_trouser2.jpg", import.meta.url).href,
  "women_trouser3.jpg": new URL("../assets/stylesense-pictures/women_trouser3.jpg", import.meta.url).href,
  "women_trouser4.jpg": new URL("../assets/stylesense-pictures/women_trouser4.jpg", import.meta.url).href,
  "women_trouser5.jpg": new URL("../assets/stylesense-pictures/women_trouser5.jpg", import.meta.url).href,
  "women_jean_pant1.jpg": new URL("../assets/stylesense-pictures/women_jean_pant1.jpg", import.meta.url).href,
  "women_jean_pant2.avif": new URL("../assets/stylesense-pictures/women_jean_pant2.avif", import.meta.url).href,
  "women_jean_pant3.avif": new URL("../assets/stylesense-pictures/women_jean_pant3.avif", import.meta.url).href,
  "women_jean_pant4.avif": new URL("../assets/stylesense-pictures/women_jean_pant4.avif", import.meta.url).href,
  "women_jean_pant5.avif": new URL("../assets/stylesense-pictures/women_jean_pant5.avif", import.meta.url).href,
  "women_jean_pant6.jpg": new URL("../assets/stylesense-pictures/women_jean_pant6.jpg", import.meta.url).href,
  "women_jean_pant7.jpg": new URL("../assets/stylesense-pictures/women_jean_pant7.jpg", import.meta.url).href,
  "women_2_piece.avif": new URL("../assets/stylesense-pictures/women_2_piece.avif", import.meta.url).href,
  "women_2_piece2.webp": new URL("../assets/stylesense-pictures/women_2_piece2.webp", import.meta.url).href,
  "women_2_piece3.png": new URL("../assets/stylesense-pictures/women_2_piece3.png", import.meta.url).href,
  "women_matching1.png": new URL("../assets/stylesense-pictures/women_matching1.png", import.meta.url).href,
  "women_matching2.png": new URL("../assets/stylesense-pictures/women_matching2.png", import.meta.url).href,
  "women_matching3.png": new URL("../assets/stylesense-pictures/women_matching3.png", import.meta.url).href,
  "women_matching4.jpg": new URL("../assets/stylesense-pictures/women_matching4.jpg", import.meta.url).href,
  "women_matching5.jpg": new URL("../assets/stylesense-pictures/women_matching5.jpg", import.meta.url).href,
};

const PRODUCT_IMAGES = [
  { match: ["black wrap maxi dress"], image: "casual_women_dress1.jpg" },
  { match: ["green tiered midi dress"], image: "casual_women_dress2.jpg" },
  { match: ["black flutter sleeve dress"], image: "casual_women_dress3.jpg" },
  { match: ["burgundy handkerchief dress"], image: "casual_women_dress4.jpg" },
  { match: ["floral swing mini dress"], image: "casual_women_dress5.jpg" },
  { match: ["gray formal skirt suit"], image: "formal_women_outfit.jpg" },
  { match: ["olive pleated formal dress"], image: "formal_women_dress1.jpg" },
  { match: ["formal sheath dress"], image: "formal_women_dress2.avif" },
  { match: ["ivory beaded maxi dress"], image: "maxi_dress1.jpg" },
  { match: ["yellow floral maxi dress"], image: "maxi_dress2.jpg" },
  { match: ["navy evening maxi dress"], image: "maxi_dress3.jpg" },
  { match: ["rose floral maxi dress"], image: "maxi_dress4.jpg" },
  { match: ["pastel bow maxi dress"], image: "maxi_dress5.jpg" },
  { match: ["champagne sequin party dress"], image: "party_dress5.jpg" },
  { match: ["emerald sequin mini dress"], image: "party_dress2.jpg" },
  { match: ["mauve satin party dress"], image: "party_dress3.jpg" },
  { match: ["red satin party dress"], image: "party_dress4.jpg" },
  { match: ["black party dress"], image: "party_dress1.jpg" },
  { match: ["gray logo hoodie"], image: "women_hoodie1.jpg" },
  { match: ["soft casual hoodie"], image: "women_hoodie3.jpg" },
  { match: ["black graphic hoodie"], image: "women_hoodie5.jpg" },
  { match: ["men's yellow sport hoodie", "yellow sport hoodie"], image: "mens_hoodie2.jpg" },
  { match: ["men's gray graphic hoodie", "gray graphic hoodie"], image: "mens_hoodie4.jpg" },
  { match: ["white puffer jacket"], image: "women_jacket1.jpg" },
  { match: ["black contrast coat"], image: "women_jacket2.jpg" },
  { match: ["cropped denim jacket"], image: "women_jacket5.webp" },
  { match: ["men's hooded utility jacket", "hooded utility jacket"], image: "mens_jacket3.jpg" },
  { match: ["men's varsity jacket", "varsity jacket"], image: "mens_jacket4.jpg" },
  { match: ["men's lightweight short sleeve shirt", "men's casual tee"], image: "mens_hoodie2.jpg" },
  { match: ["men's lightweight chinos"], image: "mens_trouser2.jpg" },
  { match: ["men's classic trousers", "classic trousers"], image: "mens_trouser1.jpg" },
  { match: ["men's drawstring trousers", "drawstring trousers"], image: "mens_trouser2.jpg" },
  { match: ["rust wide-leg trousers", "rust wide leg trousers"], image: "women_trouser3.jpg" },
  { match: ["wide-leg denim trousers", "wide leg denim trousers"], image: "women_trouser4.jpg" },
  { match: ["teal palazzo trousers", "teal palazzo pants"], image: "women_trouser5.jpg" },
  { match: ["cargo denim jeans"], image: "women_jean_pant1.jpg" },
  { match: ["straight-leg jeans", "straight leg jeans"], image: "women_jean_pant2.avif" },
  { match: ["light wash jeans"], image: "women_jean_pant3.avif" },
  { match: ["blue wide-leg jeans", "blue wide leg jeans"], image: "women_jean_pant4.avif" },
  { match: ["relaxed denim jeans"], image: "women_jean_pant5.avif" },
  { match: ["light cargo jeans"], image: "women_jean_pant6.jpg" },
  { match: ["denim statement jeans"], image: "women_jean_pant7.jpg" },
  { match: ["casual cream two-piece set", "casual cream two piece set"], image: "women_2_piece.avif" },
  { match: ["burgundy mini two-piece set", "burgundy mini two piece set"], image: "women_2_piece2.webp" },
  { match: ["blue lace short set"], image: "women_2_piece3.png" },
  { match: ["white embellished two-piece set", "white embellished two piece set"], image: "women_matching1.png" },
  { match: ["pink blazer skirt set"], image: "women_matching2.png" },
  { match: ["floral satin coord set"], image: "women_matching3.png" },
  { match: ["neutral knit matching set"], image: "women_matching4.jpg" },
  { match: ["crochet top skirt set"], image: "women_matching5.jpg" },
  { match: ["blue ruffle shirt top"], image: "women_dress_top1.jpg" },
  { match: ["floral off-shoulder crop top"], image: "women_crop_top.jpg" },
  { match: ["pink petal sleeve top"], image: "women_top5.webp" },
  { match: ["cream one-shoulder top"], image: "women_top4.jpg" },
  { match: ["red peplum blouse"], image: "women_top3.jpg" },
  { match: ["black fitted crop tee"], image: "women_crop1.jpg" },
  { match: ["white long-sleeve crop top"], image: "women_crop2.jpg" },
  { match: ["olive athletic crop top"], image: "women_crop3.jpg" },
  { match: ["neutral crop top"], image: "women_crop4.jpg" },
  { match: ["statement crop top"], image: "women_crop5.jpg" },
  { match: ["satin dressy top"], image: "women_top1.avif" },
  { match: ["soft casual top"], image: "women_top2.avif" },
  { match: ["denim mini skirt"], image: "women_skirt_avif1.avif" },
  { match: ["ribbed midi skirt"], image: "women_skirt_avif2.avif" },
  { match: ["tan button midi skirt"], image: "women_skirt_outfit1.jpg" },
  { match: ["neutral maxi skirt"], image: "women_skirt_outfit2.jpg" },
  { match: ["black pleated mini skirt"], image: "women_skirt_outfit3.jpg" },
  { match: ["floral a-line skirt"], image: "women_skirt_outfit4.jpg" },
  { match: ["black casual skirt"], image: "women_skirt_outfit5.jpg" },
  { match: ["cream pleated wrap skirt"], image: "women_skirt_style0.jpg" },
  { match: ["green slit maxi skirt"], image: "women_skirt_style3.jpg" },
  { match: ["pink ribbed midi skirt"], image: "women_skirt_style4.jpg" },
  { match: ["black pleated tennis skirt"], image: "women_skirt_style5.jpg" },
  { match: ["emerald pencil skirt"], image: "women_skirt_style6.jpg" },
  { match: ["ivory bow satin skirt"], image: "women_skirt_style7.jpg" },
  { match: ["men's black canvas sneakers"], image: "mens_shoe1.jpg" },
  { match: ["men's blue perforated sneakers"], image: "mens_shoe2.jpg" },
  { match: ["men's retro trainer sneakers"], image: "mens_shoe3.jpg" },
  { match: ["men's leopard slip-on sneakers"], image: "mens_shoe4.jpg" },
  { match: ["men's knit walking sneakers"], image: "mens_shoe5.jpg" },
  { match: ["men's brown oxford dress shoes"], image: "mens_shoe6.jpg" },
  { match: ["women's winter slip-on boots", "winter slip-on boots"], image: "women_winter_slip_on_boots.webp" },
  { match: ["women's fur-lined winter boots", "fur-lined winter boots", "winter boots"], image: "women_fur_winter_boots.webp" },
  { match: ["women's black knee-high boots", "black knee-high boots", "leather ankle boots"], image: "women_black_knee_high_boots.webp" },
  { match: ["burgundy heeled sandals"], image: "women_burgundy_heeled_sandals.webp" },
  { match: ["embellished flat sandals"], image: "women_embellished_flat_sandals.webp" },
  { match: ["metallic wedge sandals", "wedge sandals"], image: "women_wedge_sandals.webp" },
  { match: ["gold knot necklace set"], image: "accessory_gold_knot_set.webp" },
  { match: ["emerald drop earrings", "statement drop earrings"], image: "accessory_green_drop_earrings.webp" },
  { match: ["ruby necklace and earring set"], image: "accessory_ruby_necklace_set.webp" },
  { match: ["silver hoop earrings"], image: "accessory_silver_hoop_earrings.webp" },
  { match: ["gold chain necklace"], image: "accessory_gold_chain_necklace.webp" },
  { match: ["layered silver necklace"], image: "accessory_layered_silver_necklace.webp" },
  { match: ["pearl pendant necklace set"], image: "accessory_pearl_necklace_set.webp" },
  { match: ["statement silver chain necklace"], image: "accessory_statement_silver_necklace.jpg" },
  { match: ["floral", "midi", "dress"], image: "casual_dress3.avif" },
  { match: ["dress"], image: "casual_dress4.jpg" },
  { match: ["blazer", "tailored"], image: "former_outfit.jpg" },
  { match: ["coat", "trench", "outerwear"], image: "sweater6.jpg" },
  { match: ["jeans", "denim"], image: "jean_pant7.jpg" },
  { match: ["skirt"], image: "skirt9.webp" },
  { match: ["blouse"], image: "top3.jpg" },
  { match: ["men's quarter-zip", "quarter-zip", "fair isle"], image: "mens_sweater4.jpg" },
  { match: ["men's wool sweater", "mens wool sweater", "men wool sweater"], image: "mens_sweater2.jpg" },
  { match: ["cable knit", "chunky"], image: "sweater1.avif" },
  { match: ["cardigan", "strawberry"], image: "sweater6.jpg" },
  { match: ["graphic sweatshirt"], image: "sweater4.webp" },
  { match: ["gray knit", "grey knit"], image: "sweater3.avif" },
  { match: ["cashmere", "sweater"], image: "sweater5.avif" },
  { match: ["top", "shirt"], image: "top5.webp" },
  { match: ["set", "matching"], image: "2_piece2.webp" },
];

const CATEGORY_IMAGES = {
  Dresses: "casual_dress1.avif",
  Tops: "top3.jpg",
  Sweaters: "sweater5.avif",
  Bottoms: "jean_pant7.jpg",
  Mens: "mens_hoodie2.jpg",
  Outerwear: "former_outfit.jpg",
  Shoes: "women_black_knee_high_boots.webp",
  Accessories: "accessory_gold_knot_set.webp",
};

export function imageUrl(fileName) {
  return ASSET_IMAGES[fileName] || ASSET_IMAGES["2_piece.avif"];
}

export function getProductImage(product = {}) {
  if (product.imageUrl) {
    return product.imageUrl;
  }

  const text = `${product.name || ""} ${product.category || ""} ${product.style || ""}`.toLowerCase();
  const productMatch = PRODUCT_IMAGES.find((entry) =>
    entry.match.some((word) => text.includes(word))
  );

  if (productMatch) {
    return imageUrl(productMatch.image);
  }

  return imageUrl(CATEGORY_IMAGES[product.category] || "2_piece.avif");
}

export function getCategoryImage(category = "") {
  return imageUrl(CATEGORY_IMAGES[category] || "2_piece.avif");
}

export const fallbackImage = ASSET_IMAGES["2_piece.avif"];
